### ISSUE TITLE
同步微信用户和同步消息模板问题

### ISSUE THREAD

**Issue by landy8530** [niefy/wx-api#31]
1. 新用户关注时，不会自动插入到现有数据库表wx_user，需要手动点击【同步粉丝】，但是这样还有个问题，当wx_user已经有数据时，好像就同步不了，会提示重复主键的异常
2. 同步消息模板时，也是一样，会提示重复主键的异常。新增加的模板不能同步到模板表中。（后面发现，一开始会报错，然后退出系统重新登录就发现同步成功，没有退出登录，新增加的数据出不来）

**Comment by niefy** [comment]
已修复
