### ISSUE TITLE
WxMpPortalController.post 请求中requestBody 接收不到微信的XML信息

### ISSUE THREAD

**Issue by duanxiongfei** [niefy/wx-api#35]
从微信公众号中发送文本消息，在XssFilter里面调试能正常接收xml信息
但是流转到WxMpPortalController.post 始终得不到xml数据，好像是request.getInputStream()已经使用过导致的

**Comment by niefy** [comment]
暂未发现此问题，请详细描述问题出现场景、关键错误信息

**Comment by duanxiongfei** [comment]
步骤：
1、从微信公众号中发送文本消息
2、接口监听调试

XssFilter.doFilter   代码中调试获取是正常的xml字符串数据，逻辑转到WxMpPortalController.post方法`@RequestBody String requestBody`接收到的内容总是一串数字“15963364665”此数字会变化
`public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)`
`        throws IOException, ServletException {`
`       XssHttpServletRequestWrapper xssRequest = new XssHttpServletRequestWrapper(`
`           (HttpServletRequest) request);`
`       chain.doFilter(xssRequest, response);`
`   }`


我临时方案是去掉入参`@RequestBody String requestBody`,增加参数`XssHttpServletRequestWrapper requestWrapper`
`public String post(@PathVariable String appid,`
`//                @RequestBody String requestBody,`
`@RequestParam("signature") String signature,`
                  `@RequestParam("timestamp") String timestamp,`
                  `@RequestParam("nonce") String nonce,`
                  `@RequestParam("openid") String openid,`
                  `@RequestParam(name = "encrypt_type", required = false) String encType,`
                  `@RequestParam(name = "msg_signature", required = false) String msgSignature,`
                  `XssHttpServletRequestWrapper requestWrapper){`
`//临时解决方案，采用requestWrapper.getInputSteam获取内容`
`String requestBody = HttpContextUtils.ReadAsChars2(requestWrapper);`
`....`
`}`

**Comment by niefy** [comment]
请更新代码到最新版验证此问题是否依然存在

**Comment by niefy** [comment]
0.7 版本之后公众号接入地址有变更，从老版本升级的话需要重新接入
