### ISSUE TITLE
公众号菜单 view 类型后端接收出现链接地址字符串转义问题

### ISSUE THREAD

**Issue by duanxiongfei** [niefy/wx-api#37]
比如前端发送请求：https://aaa.com/a?t=1&t1=23
后台接收：https://aaa.com/a?t=1&amp;t1=23
导致微信菜单点击没反应

**Comment by landy8530** [comment]
前端你做一下encode即可

**Comment by niefy** [comment]
最新版验证可配置此链接，不过链接无效不能打开，请更新最新代码重试

**Comment by niefy** [comment]
此问题先关闭，如再次出现请提供出错的真实测试用例地址
