### ISSUE TITLE
请问关于全局默认自动回复的设置

### ISSUE THREAD

**Issue by MEZboy** [niefy/wx-api#40]
您好，请问是不是现在只能根据对应的事件key或者内容关键字去进行匹配性质的自动回复，而不能设置一个默认的全局针对所有用户的自动回复消息呢，就是比如用户随便发一个信息过来，后台返回“已收到您的消息”，谢谢

**Comment by niefy** [comment]
是的，全局默认回复可通过少量修改实现，如需定制可联系我
