### ISSUE TITLE
docker运行后端api报错，有大佬知道怎么解决嘛

### ISSUE THREAD

**Issue by wcwcwc1920** [niefy/wx-api#79]
![4841663574894_ pic](https://user-images.githubusercontent.com/39624149/190975276-2b980220-332b-4f8d-991a-38498195c3d9.jpg)

**Comment by wcwcwc1920** [comment]
解决了，问题是macos下 运行idea没有权限在/usr/local/wx/log/日期.log建立日志文件。给它建立一个就好了

**Comment by niefy** [comment]
已更新，docker启动默认使用内置H2数据库
